#!/usr/bin/env python3
"""Check overall code coverage from a Cobertura XML report (coverage.xml).

Exits with code 1 if coverage is below threshold, 0 otherwise.
Designed for CI usage (GitHub Actions annotations, outputs, and step summary).
"""

import os
import sys
import xml.etree.ElementTree as ET


def parse_coverage(xml_path: str) -> tuple[float, float]:
    """Parse coverage.xml and return (line_coverage_pct, branch_coverage_pct)."""
    tree = ET.parse(xml_path)  # nosec B314 - coverage.xml is generated by pytest-cov in CI
    root = tree.getroot()
    try:
        line_rate = float(root.attrib["line-rate"])
    except KeyError as e:
        raise ValueError("Missing attribute 'line-rate' on XML root element") from e
    except ValueError as e:
        raise ValueError("Invalid 'line-rate' value on XML root element") from e

    # Some generators can omit branch coverage; treat it as line coverage in that case.
    branch_rate_raw = root.attrib.get("branch-rate")
    if branch_rate_raw is None:
        branch_rate = line_rate
    else:
        try:
            branch_rate = float(branch_rate_raw)
        except ValueError as e:
            raise ValueError("Invalid 'branch-rate' value on XML root element") from e

    return line_rate * 100.0, branch_rate * 100.0


def validate_threshold(min_coverage: float) -> None:
    """Validate the minimum coverage threshold."""
    if not (0.0 <= min_coverage <= 100.0):  # noqa: PLR2004
        raise ValueError("min_coverage must be between 0 and 100")


def write_github_summary(
    line_coverage: float, branch_coverage: float, min_coverage: float, passed: bool
) -> None:
    """Write coverage report to GitHub Actions step summary."""
    summary_file = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_file:
        return

    with open(summary_file, "a", encoding="utf-8") as f:
        overall = min(line_coverage, branch_coverage)
        f.write("### Code Coverage Report\n\n")
        f.write("| Metric | Value |\n")
        f.write("|---|---:|\n")
        f.write(f"| Line coverage | {line_coverage:.2f}% |\n")
        f.write(f"| Branch coverage | {branch_coverage:.2f}% |\n")
        f.write(f"| Overall (min) | {overall:.2f}% |\n")
        f.write(f"| Minimum required | {min_coverage:.2f}% |\n\n")
        f.write(f"**Status:** {'PASSED' if passed else 'FAILED'}\n")
        if not passed:
            f.write(f"\nOverall coverage {overall:.2f}% is below {min_coverage:.2f}%.\n")


def write_github_annotation(
    line_coverage: float, branch_coverage: float, min_coverage: float, passed: bool
) -> None:
    """Write GitHub Actions annotation."""
    overall = min(line_coverage, branch_coverage)
    if passed:
        print(
            "::notice title=Coverage check passed "
            f"({overall:.2f}%)::"
            f"Overall coverage {overall:.2f}% meets the required {min_coverage:.2f}% threshold"
        )
    else:
        print(
            "::error title=Coverage check failed "
            f"({overall:.2f}%)::"
            f"Overall coverage {overall:.2f}% is below the required {min_coverage:.2f}% threshold"
        )


def set_github_output(line_coverage: float, branch_coverage: float) -> None:
    """Set GitHub Actions output variable."""
    output_file = os.environ.get("GITHUB_OUTPUT")
    if output_file:
        with open(output_file, "a", encoding="utf-8") as f:
            f.write(f"line_coverage={line_coverage:.2f}\n")
            f.write(f"branch_coverage={branch_coverage:.2f}\n")
            f.write(f"coverage={min(line_coverage, branch_coverage):.2f}\n")


def main() -> None:
    """Main function to check overall code coverage."""
    required_args = 2
    if len(sys.argv) < required_args + 1:
        print("Usage: check_coverage.py <coverage.xml> <min_coverage>", file=sys.stderr)
        sys.exit(1)

    coverage_xml = sys.argv[1]
    try:
        min_coverage = float(sys.argv[2])
        validate_threshold(min_coverage)
    except ValueError as e:
        print(f"Invalid min_coverage: {e}", file=sys.stderr)
        sys.exit(2)

    try:
        line_coverage, branch_coverage = parse_coverage(coverage_xml)
    except Exception as e:
        print(f"Error parsing coverage file: {e}", file=sys.stderr)
        sys.exit(1)

    passed = min(line_coverage, branch_coverage) >= min_coverage

    # Output for GitHub Actions
    set_github_output(line_coverage, branch_coverage)
    write_github_summary(line_coverage, branch_coverage, min_coverage, passed)
    write_github_annotation(line_coverage, branch_coverage, min_coverage, passed)

    # Print to console
    print(f"Line Coverage: {line_coverage:.2f}%")
    print(f"Branch Coverage: {branch_coverage:.2f}%")
    print(f"Minimum Required: {min_coverage:.2f}%")
    print(f"Status: {'PASSED' if passed else 'FAILED'}")

    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
